# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 57b65e2809d46bb0af80f857534ea771adad898a

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 57b65e2809d46bb0af80f857534ea771adad898a

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2020-10-01
Content-Type: application/json

###
DELETE {{baseUrl}}/advertisements/12/
Content-Type: application/json
Authorization: Token 1a2c5c81347476fe556613d426b47319e4fd6e86
